### ISSUE TITLE
Change Application Icon

### ISSUE THREAD

**Issue by IaamRich** [1Brain1/FRS-app#1]

**Comment by 1Brain1** [comment]
Done
![photo_2022-08-26_15-49-13](https://user-images.githubusercontent.com/100211519/186907552-d1c0cd11-a02b-4d80-841d-5cdf90daf8a7.jpg)
![photo_2022-08-26_15-49-18](https://user-images.githubusercontent.com/100211519/186907556-c75bde8d-3f03-4c07-8298-6d6b78ded167.jpg)

**Comment by 1Brain1** [comment]
Fixed Icons:
![photo_2022-08-27_18-35-04](https://user-images.githubusercontent.com/100211519/187037400-0ab1d4c6-3911-4c34-908a-59f73cb15c30.jpg)
![photo_2022-08-27_18-41-02](https://user-images.githubusercontent.com/100211519/187037401-db7f8261-408d-4d6f-be9b-4f28a44f44eb.jpg)
