### ISSUE TITLE
Other Pages

### ISSUE THREAD

**Issue by IaamRich** [1Brain1/FRS-app#19]
- Add Navigation Logic bettween the pages by pressing Dashboard menu. - All Pages just with label with its name.
- Add just LogOut button for settings page to navigate back to the Sign In Page.

**Comment by 1Brain1** [comment]
Done


https://user-images.githubusercontent.com/100211519/187712022-9b478ac3-b71a-4ec1-be82-6b3f05024d47.mp4

**Comment by 1Brain1** [comment]
![photo_2022-09-07_10-29-27](https://user-images.githubusercontent.com/100211519/188816340-3055713f-9fe6-46a0-9557-0a11c9c37343.jpg)
